apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
spec:
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: 6379
  selector:
    app: redis-uaparser
  clusterIP: None
